import fs from 'node:fs';
import path from 'node:path';

export function createTypesContent(symbolIds: string[], spritemapUrl: string): string {
  const entries = symbolIds.map(id => `  ${JSON.stringify(id)},\n`).join('');
  const list = entries ? `[\n${entries}]` : '[]';

  return `// Generated by vite-plugin-svg-spritemap. Do not edit.

export const spritemapUrl = ${JSON.stringify(spritemapUrl)};

export const iconNames = ${list} as const;

export type IconName = (typeof iconNames)[number];

export function iconHref(name: IconName): string {
  return \`\${spritemapUrl}#\${name}\`;
}
`;
}

/**
 * Writes the generated module, skipping the write when nothing changed — the
 * file usually lives inside the project source, so rewriting it would make the
 * dev server reload for no reason.
 */
export function writeTypes(filePath: string, symbolIds: string[], spritemapUrl: string): void {
  const content = createTypesContent(symbolIds, spritemapUrl);

  if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf-8') === content) {
    return;
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}
