import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, test } from 'vitest';
import { createTypesContent, writeTypes } from './writeTypes';

describe('createTypesContent', () => {
  test('should declare a const array and derive the union from it', () => {
    expect(createTypesContent(['arrow', 'close'], '/spritemap.svg')).toMatchInlineSnapshot(`
      "// Generated by vite-plugin-svg-spritemap. Do not edit.

      export const spritemapUrl = "/spritemap.svg";

      export const iconNames = [
        "arrow",
        "close",
      ] as const;

      export type IconName = (typeof iconNames)[number];

      export function iconHref(name: IconName): string {
        return \`\${spritemapUrl}#\${name}\`;
      }
      "
    `);
  });

  test('should handle an empty sprite', () => {
    expect(createTypesContent([], '/spritemap.svg')).toContain(
      'export const iconNames = [] as const;',
    );
  });

  test('should escape names that are not plain identifiers', () => {
    expect(createTypesContent(['it"s-odd'], '/spritemap.svg')).toContain('"it\\"s-odd"');
  });

  test('should carry the hashed url through', () => {
    expect(createTypesContent(['arrow'], '/assets/spritemap-a1b2c3d4.svg')).toContain(
      'export const spritemapUrl = "/assets/spritemap-a1b2c3d4.svg";',
    );
  });
});

describe('writeTypes', () => {
  test('should create missing directories and not rewrite identical content', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'svg-spritemap-types-'));
    const filePath = path.join(dir, 'nested', 'icons.ts');

    writeTypes(filePath, ['arrow'], '/spritemap.svg');
    expect(fs.readFileSync(filePath, 'utf-8')).toContain('"arrow"');

    const firstWrite = fs.statSync(filePath).mtimeMs;
    writeTypes(filePath, ['arrow'], '/spritemap.svg');
    expect(fs.statSync(filePath).mtimeMs).toBe(firstWrite);

    writeTypes(filePath, ['arrow', 'close'], '/spritemap.svg');
    expect(fs.readFileSync(filePath, 'utf-8')).toContain('"close"');

    fs.rmSync(dir, { recursive: true, force: true });
  });

  test('should rewrite when only the url changed', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'svg-spritemap-types-'));
    const filePath = path.join(dir, 'icons.ts');

    writeTypes(filePath, ['arrow'], '/spritemap-aaaaaaaa.svg');
    writeTypes(filePath, ['arrow'], '/spritemap-bbbbbbbb.svg');

    expect(fs.readFileSync(filePath, 'utf-8')).toContain('/spritemap-bbbbbbbb.svg');

    fs.rmSync(dir, { recursive: true, force: true });
  });
});
